services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=AmitSahoo@454545
    ports:
      - 6969:6969
    volumes:
      - /var/lib/postgresql/data

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - /data/db
      
